# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# reload config file
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

# moar history
set -g history-limit 111111

# replace C-a l to C-a C-a
unbind l
bind C-a last-window

# alternative screen config
set-window-option -g alternate-screen off

# increase display-time
set -g display-time 1500

# status line
set -g status-right "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,} %Y-%m-%d %H:%M"
set -g status-interval 0

# execute command instead shell
set -g default-command bash

# emacs keys for copy
set-window-option -g mode-keys emacs

# set color terminal
set -g default-terminal "tmux-256color"
set -g status-bg colour8
set -g status-fg white

# force tmux to use OSC52 for applications that support 'Ms'
set -as terminal-overrides ',tmux*:Ms=\E]52;c;%p2%s\a'
set -as terminal-overrides ',xterm*:Ms=\E]52;c;%p2%s\a'
set -as terminal-overrides ',screen*:Ms=\E]52;c;%p2%s\a'

# Allow OSC52 passthrough
set -g allow-passthrough on
set -g set-clipboard on
